#!/usr/bin/env bash
# Pings an IP address received as an argument 5 times.

# Check if an argument was passed
if [ $# -eq 0 ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

# Ping the IP address 5 times
ping -c 5 "$1"
